### ISSUE TITLE
[Bug] "Private key parameters don't match with public key's!" 

### ISSUE THREAD

**Issue by Mosrite** [whiteout-io/mail-html5#384] opened 2015-06-22 12:09 UTC
Hey, I already filed a bug report email but noone responded yet, so I'll just post it here:

*Steps to reproduce*
1. Logging in with Whiteout (webmail) for the first time, importing a valid PGP-key formerly created with Enigmail (Thunderbird Extension). [Everything works fine, emails that have already been encrypted can be decrypted by the webmail apllication. Emails can be sent.]
2. Trying to access Whiteout from another device. Typing in email address and email password. [Everything fine so far]. 
3. Typing in backup code.

*What happens?*
Error: "Private key parameters don't match with public key's!" Unable to log in.

*What do you expect to happen instead?*
Logging in seamlessly.

Thanks in advance for any help!

**Comment by felixhammerl** [comment] 2015-07-07 09:32
duplicate of https://github.com/whiteout-io/mail-html5/issues/301

**Closed by felixhammerl** 2015-07-07 09:32 UTC
