### ISSUE TITLE
add conversation view like gmail/mailpile

### ISSUE THREAD

**Issue by pravi** [whiteout-io/mail-html5#241] opened 2015-01-07 12:44 UTC
conversation view is a real time saver when you have big threads. People familiar with gmail interface would expect such a feature in any email app.

**Comment by xokvictor** [comment] 2015-02-15 17:53
+1

**Comment by jancborchardt** [comment] 2015-03-12 12:30
This seems to be a duplicate of issue https://github.com/whiteout-io/mail-html5/issues/92?

**Closed** 2015-06-16 15:21 UTC
Labels: enhancement
